---
abstract: 'OpenID authen hander for mod_perl2.'
author:
  - 'Nobuo Danjou, L<nobuo.danjou@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-AuthenOpenID
no_index:
  directory:
    - inc
    - t
requires:
  CGI: 0
  Class::Data::Inheritable: 0
  Digest::HMAC_SHA1: 1.01
  LWPx::ParanoidAgent: 1.03
  Net::OpenID::Consumer: 0.14
  mod_perl2: 2.000001
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
